# version: '3'

# volumes:
#   pg_data:
#   static:
#   media:

# services:
#   db:
#     image: postgres:13
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     env_file: .env
#   backend:
#     image: aadgnv/kittygram_backend
#     env_file: .env
#     depends_on:
#       - db
#     volumes:
#       - static:/app/collected_static/
#       - media:/app/media
#   frontend:
#     env_file: .env
#     image: aadgnv/kittygram_frontend
#     command: cp -r /app/build/. /static/
#     volumes:
#       - static:/static
#   gateway:
#     image: aadgnv/kittygram_gateway
#     env_file: .env
#     ports:
#       - 9000:80
#     volumes:
#       - static:/static
#       - media:/media